### ISSUE TITLE
Advanced Tables not working in Admonition

### ISSUE THREAD

**Issue by daniellsh** [javalent/admonitions#163] opened 2022-01-26 06:54 UTC
I noticed that Advanced tables stop working in Admonition recently, after I updated both plugin. Now within the code block of Admonition, the Advance Table stop auto generated like it used to be. But when outside the Admonition code block the tables are working fine. Not sure if anyone else encountered the same problem?

current version:
- Obsidian: v0.13.19
- Admonition: v6.9.7
- Advanced Tables: v0.17.2

**Comment by valentine195** [comment] 2022-01-26 11:45
This is likely due to an old bug between markdown processors. Try disabling Admonitions, restarting Obsidian, and re-enabling Admonitions.

**Comment by BrandonSLockey** [comment] 2022-02-06 11:19
> This is likely due to an old bug between markdown processors. Try disabling Admonitions, restarting Obsidian, and re-enabling Admonitions.

Admonitions table will render, but pressing Tab to create table or using any of these Menu options:

![image](https://user-images.githubusercontent.com/72495991/152678306-13290294-451c-4046-8b58-2ad8450896c6.png)
 
does not work inside the admonitions block despite restarting/re-enabling

**Comment by sigrunixia** [comment] 2023-05-28 16:26
After doing some extensive testing, I can confirm this behavior is still present. However, I suspect this is not something that can be fixed because of how the code block tries to process code by prism's rules and expectations (and admonitions, being a code block), is subject to this. 

Advanced Tables, as well, is unable to detect that a table exists within the code block. 

I am going to close this thread as the workaround to this to create the table outside the code block and surround it by an admonition code block. This is more than just an Admontions issue (as the same thing happens in other codeblocks), so this now feature request, as it was changes within Obsidian that changed the behavior in the first place, is more suited for the Obsidian forums.

**Closed by sigrunixia** 2023-05-28 16:26 UTC
Labels: discovery
